/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.booking.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author I524925
 */


public class AddEmp extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form AddEmp
     */
    public AddEmp() {
        initComponents();
        
               try {
            Class.forName("org.postgresql.Driver");
            String databaseURL = "jdbc:postgresql://localhost:5432/postgres";
            Connection con = DriverManager.getConnection(databaseURL, "postgres", "admin");
            Statement stat = con.createStatement();

            String selectQuery = "select bus_num from bus_details";

            ResultSet rs = stat.executeQuery(selectQuery);
            

         while(rs.next()){
             String bus_num = rs.getString("bus_num");
         jComboBox1.addItem(bus_num);
         }

 con.close();
            
        } catch (Exception e) {
            System.out.println(e);
        }
            
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        empNameTF = new javax.swing.JTextField();
        empIdTF = new javax.swing.JTextField();
        empPhTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(650, 443));
        setMinimumSize(new java.awt.Dimension(650, 443));
        setPreferredSize(new java.awt.Dimension(650, 443));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("NAME ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 99, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("EMP ID ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 99, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("PHONE NUMBER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 99, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("MAP TO : (BUS#)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 120, -1));
        getContentPane().add(empNameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 161, -1));
        getContentPane().add(empIdTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 161, -1));
        getContentPane().add(empPhTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 160, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("+91");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jButton1.setBackground(new java.awt.Color(254, 255, 240));
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        jButton2.setBackground(new java.awt.Color(254, 255, 240));
        jButton2.setText("Reset");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 69, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("ADD EMPLOYEE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 160, -1));

        jLabel1.setBackground(new java.awt.Color(254, 255, 240));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/oleg-laptev-EA7vfFpTJB4-unsplash.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
      /*  
       try {
            Class.forName("org.postgresql.Driver");
            String databaseURL = "jdbc:postgresql://localhost:5432/postgres";
            Connection con = DriverManager.getConnection(databaseURL, "postgres", "admin");
            Statement stat = con.createStatement();

            String selectQuery = "select bus_num from bus_details";

            ResultSet rs = stat.executeQuery(selectQuery);
            

         while(rs.next()){
             String bus_num = rs.getString("bus_num");
         jComboBox1.addItem(bus_num);
         }

 con.close();
            
        } catch (Exception e) {
            System.out.println(e);
        }
         */   
            
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
      /*   try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String databaseURL = "jdbc:postgresql://localhost:5432/postgres";
            Connection con = DriverManager.getConnection(databaseURL, "postgres", "admin");
            Statement stat = con.createStatement();

            String selectQuery = "select bus_num from bus_details";

            ResultSet rs = stat.executeQuery(selectQuery);
            
while(rs.next()){
           System.out.print(rs.getString(1));
           jLabel7.setText(rs.getString(1));
           jComboBox1.addItem(rs.getString(1));

}
            
        } catch (Exception e) {
            System.out.println(e);
        }
*/
            
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField empIdTF;
    private javax.swing.JTextField empNameTF;
    private javax.swing.JTextField empPhTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
