/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.booking.system;

/**
 *
 * @author I524925
 */
public class AddSeat extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    public AddSeat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        seat1 = new javax.swing.JCheckBox();
        seat2 = new javax.swing.JCheckBox();
        seat3 = new javax.swing.JCheckBox();
        seat4 = new javax.swing.JCheckBox();
        seat5 = new javax.swing.JCheckBox();
        seat6 = new javax.swing.JCheckBox();
        seat7 = new javax.swing.JCheckBox();
        seat8 = new javax.swing.JCheckBox();
        seat9 = new javax.swing.JCheckBox();
        seat10 = new javax.swing.JCheckBox();
        seat11 = new javax.swing.JCheckBox();
        seat12 = new javax.swing.JCheckBox();
        seat13 = new javax.swing.JCheckBox();
        seat14 = new javax.swing.JCheckBox();
        seat15 = new javax.swing.JCheckBox();
        seat16 = new javax.swing.JCheckBox();
        seat17 = new javax.swing.JCheckBox();
        seat18 = new javax.swing.JCheckBox();
        seat19 = new javax.swing.JCheckBox();
        seat20 = new javax.swing.JCheckBox();
        seat21 = new javax.swing.JCheckBox();
        seat22 = new javax.swing.JCheckBox();
        seat23 = new javax.swing.JCheckBox();
        seat24 = new javax.swing.JCheckBox();
        seat25 = new javax.swing.JCheckBox();
        seat26 = new javax.swing.JCheckBox();
        seat27 = new javax.swing.JCheckBox();
        seat28 = new javax.swing.JCheckBox();
        seat29 = new javax.swing.JCheckBox();
        seat30 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seat1.setText("01");
        seat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat2.setText("02");
        seat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat3.setText("03");
        seat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat4.setText("04");
        seat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N
        seat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat4ActionPerformed(evt);
            }
        });

        seat5.setText("05");
        seat5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat6.setText("06");
        seat6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat7.setText("07");
        seat7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat8.setText("08");
        seat8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat9.setText("09");
        seat9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat10.setText("10");
        seat10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat11.setText("11");
        seat11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N
        seat11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat11ActionPerformed(evt);
            }
        });

        seat12.setText("12");
        seat12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat13.setText("13");
        seat13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N
        seat13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat13ActionPerformed(evt);
            }
        });

        seat14.setText("14");
        seat14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N
        seat14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat14ActionPerformed(evt);
            }
        });

        seat15.setText("15");
        seat15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N
        seat15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat15ActionPerformed(evt);
            }
        });

        seat16.setText("16");
        seat16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat17.setText("17");
        seat17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat18.setText("18");
        seat18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat19.setText("19");
        seat19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat20.setText("20");
        seat20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat21.setText("21");
        seat21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat22.setText("22");
        seat22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat23.setText("23");
        seat23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N
        seat23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat23ActionPerformed(evt);
            }
        });

        seat24.setText("24");
        seat24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat25.setText("25");
        seat25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat26.setText("26");
        seat26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat27.setText("27");
        seat27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat28.setText("28");
        seat28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat29.setText("29");
        seat29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        seat30.setText("30");
        seat30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/seat.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/door.png"))); // NOI18N
        jLabel1.setText("Door");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/steering-wheel-2034359-1714709.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setText("Selected Seats ");

        jLabel4.setText("Booking  Amount ");

        jButton1.setText("Next >>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seat16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat17)
                                .addGap(107, 107, 107)
                                .addComponent(seat18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seat20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seat11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat12)
                                .addGap(107, 107, 107)
                                .addComponent(seat13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seat15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seat6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat7)
                                .addGap(107, 107, 107)
                                .addComponent(seat8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seat10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seat26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat27)
                                .addGap(107, 107, 107)
                                .addComponent(seat28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seat30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seat21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat22)
                                .addGap(107, 107, 107)
                                .addComponent(seat23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seat25))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seat1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat2)
                                .addGap(107, 107, 107)
                                .addComponent(seat3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(seat4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seat5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat26)
                    .addComponent(seat27)
                    .addComponent(seat28)
                    .addComponent(seat29)
                    .addComponent(seat30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat21)
                    .addComponent(seat22)
                    .addComponent(seat23)
                    .addComponent(seat24)
                    .addComponent(seat25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat16)
                    .addComponent(seat17)
                    .addComponent(seat18)
                    .addComponent(seat19)
                    .addComponent(seat20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat11)
                    .addComponent(seat12)
                    .addComponent(seat13)
                    .addComponent(seat14)
                    .addComponent(seat15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat6)
                    .addComponent(seat7)
                    .addComponent(seat8)
                    .addComponent(seat9)
                    .addComponent(seat10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seat1)
                    .addComponent(seat2)
                    .addComponent(seat3)
                    .addComponent(seat4)
                    .addComponent(seat5))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seat11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat11ActionPerformed

    private void seat13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat13ActionPerformed

    private void seat14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat14ActionPerformed

    private void seat15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat15ActionPerformed

    private void seat23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat23ActionPerformed

    private void seat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seat4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSeat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JCheckBox seat1;
    private javax.swing.JCheckBox seat10;
    private javax.swing.JCheckBox seat11;
    private javax.swing.JCheckBox seat12;
    private javax.swing.JCheckBox seat13;
    private javax.swing.JCheckBox seat14;
    private javax.swing.JCheckBox seat15;
    private javax.swing.JCheckBox seat16;
    private javax.swing.JCheckBox seat17;
    private javax.swing.JCheckBox seat18;
    private javax.swing.JCheckBox seat19;
    private javax.swing.JCheckBox seat2;
    private javax.swing.JCheckBox seat20;
    private javax.swing.JCheckBox seat21;
    private javax.swing.JCheckBox seat22;
    private javax.swing.JCheckBox seat23;
    private javax.swing.JCheckBox seat24;
    private javax.swing.JCheckBox seat25;
    private javax.swing.JCheckBox seat26;
    private javax.swing.JCheckBox seat27;
    private javax.swing.JCheckBox seat28;
    private javax.swing.JCheckBox seat29;
    private javax.swing.JCheckBox seat3;
    private javax.swing.JCheckBox seat30;
    private javax.swing.JCheckBox seat4;
    private javax.swing.JCheckBox seat5;
    private javax.swing.JCheckBox seat6;
    private javax.swing.JCheckBox seat7;
    private javax.swing.JCheckBox seat8;
    private javax.swing.JCheckBox seat9;
    // End of variables declaration//GEN-END:variables
}
