/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.booking.system;

import bus.booking.system.AddSeat;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author I524923
 */
public class BookingScreen extends javax.swing.JFrame {

    /**
     * Creates new form BookingScreen
     */
    public BookingScreen() {
        initComponents();
    }
    AddSeat seat;
    String Source;
    String Destination;
    String Bus_no;
    int fare;
    AddSeat seat_object = new AddSeat();
    int tot_seats;
    
    public BookingScreen(int i, String source, String destination, String bus_no, int total_seats){
         initComponents();
         
        tot_seats = total_seats; 
        this.Source = source;
        this.Destination= destination;
        this.Bus_no=bus_no;
       
        
        String getVal = pName.getText();
        String getVal1 = pAge.getText();
        pName.setText(getVal+" " + i);
        pAge.setText(getVal1 +" "+  i);
        busNo.setText(Bus_no);
        
        try {
            Class.forName("org.postgresql.Driver");
            String databaseURL = "jdbc:postgresql://localhost:5432/postgres";
            Connection con = DriverManager.getConnection(databaseURL, "postgres", "admin");
            
           String selectQuery = "select * from bus_details where bus_num='" +Bus_no  + "'";        
           Statement stat = con.createStatement();

           ResultSet rs = stat.executeQuery(selectQuery);
           
           
            while(rs.next()){
           int price = rs.getInt("price");
           int total_price = tot_seats*price;
           Price.setText(Integer.toString(total_price));
           fare = total_price;
            
             };
           
            
         }catch(Exception e){
         System.out.println(e);
         }
       
        
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pName = new javax.swing.JLabel();
        tName = new javax.swing.JTextField();
        tAge = new javax.swing.JTextField();
        pAge = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        M = new javax.swing.JRadioButton();
        F = new javax.swing.JRadioButton();
        O = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Confirm = new javax.swing.JButton();
        tSeat = new javax.swing.JTextField();
        pickSeat = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        busNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Price = new javax.swing.JTextField();
        Fetch = new javax.swing.JButton();
        Next = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, -1));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel2.setText("Passenger Details");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 210, -1));

        pName.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        pName.setText("Passenger");
        getContentPane().add(pName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 90, 30));
        getContentPane().add(tName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 180, 20));
        getContentPane().add(tAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 180, 20));

        pAge.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        pAge.setText("Passenger ");
        getContentPane().add(pAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, -1));

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 100, -1));

        buttonGroup1.add(M);
        M.setText("Male");
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });
        getContentPane().add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        buttonGroup1.add(F);
        F.setText("Female");
        getContentPane().add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        buttonGroup1.add(O);
        O.setSelected(true);
        O.setText("Other");
        getContentPane().add(O, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel4.setText("Seat ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        Confirm.setText("Confirm");
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(Confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 100, -1));

        tSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSeatActionPerformed(evt);
            }
        });
        getContentPane().add(tSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 130, -1));

        pickSeat.setText("Pick Seat");
        pickSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickSeatActionPerformed(evt);
            }
        });
        getContentPane().add(pickSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 100, -1));

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel5.setText("Bus No");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel6.setText("Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 74, 50, 20));

        busNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busNoActionPerformed(evt);
            }
        });
        getContentPane().add(busNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 80, -1));

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel7.setText("Age");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 50, 20));

        jLabel8.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        jLabel8.setText("Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 130, -1));

        Fetch.setText("Fetch");
        Fetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FetchActionPerformed(evt);
            }
        });
        getContentPane().add(Fetch, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        Next.setLabel("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/oli-dale-xjSkI_seiZY-unsplash (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 570, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
     // TODO add your handling code here:
      String Name = tName.getText();
     String Age= tAge.getText();
     String Seat= tSeat.getText();
     String bus_no = busNo.getText();
     System.out.println(Name);
     String Gender  ; 
     if(M.isSelected()==true)
     {
     Gender = M.getText();
     }
     else if(F.isSelected()==true)
     {
     Gender = F.getText();
     }
      else
     {
     Gender = O.getText();
     }
     
     
     if(Name.isEmpty()==true || Age.isEmpty()==true || Seat.isEmpty()==true){
     JOptionPane.showMessageDialog(null,"Please enter the required information!");
     }
     else
     {

     try {
            Class.forName("org.postgresql.Driver");
            String databaseURL = "jdbc:postgresql://localhost:5432/postgres";
            Connection con = DriverManager.getConnection(databaseURL, "postgres", "admin");
            Statement stat = con.createStatement();

           // String selectQuery = "select count(*) from bus_details where bus_num='" + bus_num + "'";

          //  ResultSet rs = stat.executeQuery(selectQuery);

           // if(Integer.parseInt(total_seats) > 30){
           // JOptionPane.showMessageDialog(null,"Max Seats: 30");
          //  }
          
               
                
                String insertQuery = "insert into bus_bookings(passenger_name, passenger_age, bus_num,gender, seat) values('" + Name + "','" + Age + "','" + bus_no + "','" + Gender + "','" + Seat  + "')" ;
                int x = stat.executeUpdate(insertQuery);
               if(x>0){
               JOptionPane.showMessageDialog(null,"Ticket for Passenger "+ Name +" Blocked." );
               }                
                
     
            
        } catch (Exception e) {
            System.out.println(e);
        }
     
     JOptionPane.showMessageDialog(null,"You need to pay Rs "+fare+" after you board your Bus! Thank You!");
     dispose();
     
    // int noSeats = Integer.parseInt(Seat);
     
       // JOptionPane.showMessageDialog(null,"Ticket booked! for "+ Name);
         
     }
    }//GEN-LAST:event_ConfirmActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MActionPerformed

    private void tSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSeatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSeatActionPerformed

    private void pickSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickSeatActionPerformed
        // TODO add your handling code here:
        
     //int noSeats = Integer.parseInt(Seat);
      String s;
      String bus_num = busNo.getText();
        seat = new AddSeat(1,bus_num);
        seat.setLocationRelativeTo(null);
        seat.setVisible(true);
        
        
     
      //tSeat.setText(s);
        
    }//GEN-LAST:event_pickSeatActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_CancelActionPerformed

    private void busNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busNoActionPerformed

    private void FetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FetchActionPerformed
        // TODO add your handling code here:
        
        String val;
        val = seat.getSeat();
        System.out.println(val);
        tSeat.setText(val);
    }//GEN-LAST:event_FetchActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NextActionPerformed

    
    public void Seat(){
    String s = seat_object.getSeat();
    tSeat.setText(s);
    
    } /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Confirm;
    private javax.swing.JRadioButton F;
    private javax.swing.JButton Fetch;
    private javax.swing.JRadioButton M;
    private java.awt.Button Next;
    private javax.swing.JRadioButton O;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField busNo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pAge;
    private javax.swing.JLabel pName;
    private javax.swing.JButton pickSeat;
    private javax.swing.JTextField tAge;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField tSeat;
    // End of variables declaration//GEN-END:variables


}
