/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.booking.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author I524917
 */
public class DeleteEmp extends javax.swing.JInternalFrame {

    /**
     * Creates new form DeleteEmp
     */
    public DeleteEmp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("BentonSans Bold", 3, 18)); // NOI18N
        jLabel5.setText("DELETE EMPLOYEE DETAILS ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 15, -1, -1));

        jLabel1.setFont(new java.awt.Font("BentonSans Bold", 3, 14)); // NOI18N
        jLabel1.setText("Please enter the EMP ID to delete employee from the database.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 55, 470, -1));

        jLabel2.setFont(new java.awt.Font("BentonSans Book Italic", 1, 12)); // NOI18N
        jLabel2.setText("EMP ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 178, 59, 20));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 178, 150, -1));

        jButton1.setFont(new java.awt.Font("BentonSans Bold", 1, 10)); // NOI18N
        jButton1.setText("I AM SURE I WANT TO DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 322, -1, -1));

        jButton2.setFont(new java.awt.Font("BentonSans Bold", 1, 10)); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 322, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void infoMessage(String message, String title) {
        JOptionPane.showMessageDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String eid = jTextField1.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String databaseURL = "jdbc:postgresql://localhost:5432/postgres";
            Connection con = DriverManager.getConnection(databaseURL, "postgres", "Stuti@12345");
            Statement stat = con.createStatement();

            String selectQuery = "select count(*) from emp_details where eid='" + eid + "'";

            ResultSet rs = stat.executeQuery(selectQuery);

            System.out.println(rs.next());
            if (rs.next() == true) {
                infoMessage("Employee doesn't exit ", "Try again!");

            } else {
                //infoMessage("Employee doesn't exit ", "Try again!");
                String Query = "DELETE FROM emp_details where eid='" + eid + "'";
                int x = stat.executeUpdate(Query);
                if (x == 1) {
                    infoMessage("Employee details successfully deleted ", " Great work ! :D  ");
                    dispose();
                }

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
