/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.booking.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author I524925
 */
public class DeleteBus extends javax.swing.JInternalFrame {

    /**
     * Creates new form DeleteBus
     */
    public DeleteBus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bus_numTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Please enter the BUS ID to delete bus from the database.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("DELETE BUS DETAILS ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 26, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("BUS ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 87, -1));
        getContentPane().add(bus_numTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 123, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 240));
        jButton1.setText("I am sure I want to delete ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 270, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/booking/system/oleg-laptev-EA7vfFpTJB4-unsplash.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(650, 443));
        jLabel3.setMinimumSize(new java.awt.Dimension(650, 443));
        jLabel3.setPreferredSize(new java.awt.Dimension(650, 443));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 670, 450));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("DELETE BUS DETAILS ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 26, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void infoMessage(String message, String title) {
        JOptionPane.showMessageDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String bus_num = bus_numTF.getText();
         try {
            Class.forName("org.postgresql.Driver");
            String databaseURL = "jdbc:postgresql://localhost:5432/postgres";
            Connection con = DriverManager.getConnection(databaseURL, "postgres", "admin");
            Statement stat = con.createStatement();

            String selectQuery = "select bus_num from bus_details where bus_num='" + bus_num + "'";

            ResultSet rs = stat.executeQuery(selectQuery);
            
            if(rs.next()==true){
            //JOptionPane.showMessageDialog(null,"Bus Found!");
              String Query = "DELETE FROM bus_details where bus_num='" + bus_num + "'";
             ResultSet x = stat.executeQuery(Query);
             if(x.next()==true)
             {
             JOptionPane.showMessageDialog(null,"Bus Deleted!");
             }
            
            }
            else{
            JOptionPane.showMessageDialog(null,"Bus not Found!");
            }
           // String Query = "DELETE FROM bus_details where bus_num='" + bus_num + "'";
            //    stat.executeQuery(Query);

           // System.out.println(rs.next());
            /*
            if (rs.next() == true) {
                String Query = "DELETE FROM bus_details where bus_num='" + bus_num + "'";
                stat.executeQuery(Query);

                infoMessage("Bus details successfully deleted ", " Great work ! :D  ");
            } */
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bus_numTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
