/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus.booking.system;
import java.sql.*;
import java.util.Random;
import javax.swing.JOptionPane;
  
/**
 *
 * @author I524925
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fnameTF = new javax.swing.JTextField();
        lnameTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        emailTF = new javax.swing.JTextField();
        confirm = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        unameTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ageTF = new javax.swing.JTextField();
        SignIn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        genderTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("First Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 110, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Age");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 40, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Email-Id");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 70, -1));

        fnameTF.setBorder(null);
        fnameTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(fnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 170, 30));

        lnameTF.setBorder(null);
        lnameTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(lnameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 180, 30));

        passwordTF.setBorder(null);
        passwordTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTFActionPerformed(evt);
            }
        });
        getContentPane().add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 170, 30));

        emailTF.setBorder(null);
        emailTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(emailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 179, 30));

        confirm.setBackground(new java.awt.Color(73, 171, 213));
        confirm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("Confirm");
        confirm.setBorder(null);
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 110, 40));

        reset.setBackground(new java.awt.Color(73, 171, 213));
        reset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("Reset");
        reset.setBorder(null);
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 110, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("User Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 80, -1));

        unameTF.setBorder(null);
        unameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameTFActionPerformed(evt);
            }
        });
        getContentPane().add(unameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 170, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Last Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, 30));

        ageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTFActionPerformed(evt);
            }
        });
        getContentPane().add(ageTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 170, 30));

        SignIn.setText("Already Registered ? Sign In");
        SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInActionPerformed(evt);
            }
        });
        getContentPane().add(SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 230, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 80, -1));

        genderTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTFActionPerformed(evt);
            }
        });
        getContentPane().add(genderTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 180, -1));

        jLabel8.setText("Type F for female , M for Male, O for other ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void infoMessage(String message,String title)
    {
        JOptionPane.showMessageDialog(null,message,title,JOptionPane.INFORMATION_MESSAGE);
    }
    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
String fname = fnameTF.getText();
String lname= lnameTF.getText();
String uname= unameTF.getText();
String password= passwordTF.getText();
String email= emailTF.getText();
String gender= genderTF.getText();
String age = ageTF.getText();


try 
{
Class.forName("com.mysql.cj.jdbc.Driver");
String databaseURL = "jdbc:postgresql://localhost:5432/postgres";
Connection con = DriverManager.getConnection(databaseURL, "postgres", "admin");
Statement stat =con.createStatement();

String selectQuery = "select count(*) from new_user where uname='"+uname+"' and password='"+password+"'";
System.out.println(selectQuery);
ResultSet rs= stat.executeQuery(selectQuery);
System.out.println(rs.next());
if(rs.next()==true)
{
  infoMessage("Hmm.. seems like you are already registered ! "," ALert ");   
}
else

{
    
    String insertQuery = "insert into new_user(uname,fname,lname,password,email,age,gender) values('"+uname+"','"+fname+"','"+lname+"','"+password+"','"+email+"','"+age+"','"+gender+"')";
    int x= stat.executeUpdate(insertQuery);
    System.out.print(x);
    if(x==1)
    {
        infoMessage("User Registered ", " Welcome Rookie ");
        dispose();
//        Userlogon ln = new Userlogon();
//        ln.setLocationRelativeTo(null);
//        ln.setVisible(true);
    }
}
    
    

}
catch(Exception e)
        {
            System.out.println(e);
        }




        // TODO add your handling code here:
    }//GEN-LAST:event_confirmActionPerformed

    private void passwordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTFActionPerformed

    private void unameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameTFActionPerformed

    private void ageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTFActionPerformed

    private void SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInActionPerformed
    
        dispose();
        UserLogon user_logon = new UserLogon();
    //user_logon.setVisible(true);
    


        // TODO add your handling code here:
    }//GEN-LAST:event_SignInActionPerformed

    private void genderTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignIn;
    private javax.swing.JTextField ageTF;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField emailTF;
    private javax.swing.JTextField fnameTF;
    private javax.swing.JTextField genderTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lnameTF;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton reset;
    private javax.swing.JTextField unameTF;
    // End of variables declaration//GEN-END:variables
}
